@baseUrl = http://localhost:3333
//@token =dfdfsfdds

## Status Sensors

###Rota Teste 
GET {{baseUrl}}/teste

###Insert Device
POST {{baseUrl}}/device
Content-Type: application/json

  {
    "name": "casa30",
    "sensorFS": "on",
    "sensorBS": "on",
    "sensorRS": "on",
    "sensorLS": "on"
  }

###List Devices 
GET {{baseUrl}}/devices

###Delete Device
DELETE {{baseUrl}}/device/?id=6744601b89a50f5a020b09e5

###Update Device
PUT {{baseUrl}}/device/up/?id=674521b9f98dd0c0fc1d00fd
Content-Type: application/json

  {
    "name": "casa28",
    "sensorFS": "on",
    "sensorBS": "on",
    "sensorRS": "on",
    "sensorLS": "on",
    "active": false
  }
