@baseUrl = http://localhost:3333
//@token =dfdfsfdds

## Status Sensors

###Rota Teste 
GET {{baseUrl}}/teste

###Insert Device
POST {{baseUrl}}/device
Content-Type: application/json

  {
    "name": "casa28",
    "sensorFS": "on",
    "sensorBS": "on",
    "sensorRS": "on",
    "sensorLS": "on",
    "status": true
  }

###List Devices 
GET {{baseUrl}}/devices